### ISSUE TITLE
Move to next line automatically

### ISSUE THREAD

**Issue by mbetrifork** [henri5/completeline#7]
For completions that adds to the end of the line (add semicolon, colon) I would like to move to the next line automatically. Right now I find myself having to press ctrl+shift+enter twice, so the plugin doesn't actually save me any keypresses :-)

Example:

```
switch (x) {
   case 999
```

Ctrl+Shift+Enter here will then add the colon _and_ insert a blank line and move to the correctly indented position.

Possible?

**Comment by henri5** [comment]
As the plugin is ripoff from IntelliJ, it mimics its behaviour, which is not to go to next line if adding semicolon. I personally like this behaviour, because not always I want to add extra line. However I could add some extra keybind to do the exact behaviour you're looking for.

**Comment by henri5** [comment]
Ctrl+Shift+N is now in version 0.2.5 configured to also add new line as you wished for.

**Comment by mbetrifork** [comment]
I'll take a look at the new version - thanks for taking time to add this :-)

I would however like even more if the behavior was configurable somehow. I.e. have CompleteLine appear in the preferences window, with a single option "[x] Complete also adds line" or something like this. Because Ctrl+Alt+N is not quite as easy to use as ctrl+shift+enter :-)

**Comment by henri5** [comment]
You can switch the keybinds around (Ctrl+Shift+L twice or Preferences > General > Keys). It seemed simpler to do it like this now, however should any other request come up for being able to configure some behaviour, will need to implement a preferences page.

**Comment by mbetrifork** [comment]
Ok I'll try this - this is fine.

Will the marketplace be updated with the new version?

**Comment by henri5** [comment]
I updated the [repo](https://github.com/henri5/completeline-updatesite/) backing the marketplace, so yes, it is updated.
