### ISSUE TITLE
Does not work anymore with Version: 2020-03 (4.15.0)

### ISSUE THREAD

**Issue by yssoe** [henri5/completeline#9]
I can't install it from the marketplace (does not work with the current version) and it does not work in Eclipse Version: 2020-03 (4.15.0) anymore. 

Cheers

**Comment by henri5** [comment]
I bumped the supported versions in Eclipse Marketplace, seemed to fix the problem.

**Comment by yssoe** [comment]
Thanks, works perfect now @henri5
